# Prettier Options: https://prettier.io/docs/en/options.html
semi: false
printWidth: 100
# Svelte Prettier: https://github.com/sveltejs/prettier-plugin-svelte
svelteSortOrder: "scripts-markup-styles"
svelteStrictMode: false
svelteBracketNewLine: false
svelteAllowShorthand: true
svelteIndentScriptAndStyle: true
